name: Developer Hub
markdown: kramdown
#kramdown:
#  input: GFM

kramdown:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data",  "no_intra_emphasis", "fenced_code_blocks"]

highlighter: pygments
safe: true
baseurl: /developers
exclude: ['.ruby-version', 'node_modules', 'package.json', 'bower.json']
sass:
  sass_dir: static/_sass

# Blog/Post configuration
paginate: 5
paginate_path: "blog/page:num"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      organization-name: "Regulations.gov"
      organization-url: "http://regulations.gov"
      organization-contact: "http://www.regulations.gov/#!contactUs"
      organization-system: "Regulations"
      site-name: /developers
